# Generated by Django 4.0 on 2022-01-03 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=128, unique=True, verbose_name='Nom de la société')),
                ('siret', models.CharField(max_length=32, unique=True, verbose_name='Numéro de Siret')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nom du métier')),
            ],
        ),
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='Inconnu', max_length=128, verbose_name='Prénom')),
                ('lastName', models.CharField(default='Inconnu', max_length=128, verbose_name='Nom de famille')),
                ('proposer', models.IntegerField(default=1)),
                ('role', models.IntegerField(default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('jobs', models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='backBatiUni.job')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.user')),
            ],
        ),
    ]
