# Generated by Django 4.0.2 on 2022-02-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nom de la société')),
                ('siret', models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name='Numéro de Siret')),
                ('address', models.CharField(default=None, max_length=256, null=True, unique=True, verbose_name="Adresse de l'entreprise")),
                ('activity', models.CharField(default=None, max_length=256, null=True, verbose_name="Activite principale de l'entreprise")),
                ('ntva', models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name='Numéro de TVA intra communautaire')),
                ('capital', models.IntegerField(default=None, null=True, verbose_name="Capital de l'entreprise")),
                ('revenue', models.FloatField(default=None, null=True, verbose_name="Capital de l'entreprise")),
                ('logo', models.CharField(default=None, max_length=256, null=True, verbose_name="Path du logo de l'entreprise")),
                ('webSite', models.CharField(default=None, max_length=256, null=True, verbose_name='Url du site Web')),
                ('stars', models.IntegerField(default=None, null=True, verbose_name="Notation sous forme d'étoile")),
                ('companyPhone', models.CharField(default=None, max_length=128, null=True, verbose_name='Téléphone du standard')),
                ('amount', models.FloatField(default=None, null=True, verbose_name='Montant sous-traitant')),
                ('unity', models.CharField(default=None, max_length=64, null=True, verbose_name='Unité du montant')),
                ('latitude', models.FloatField(default=None, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=None, null=True, verbose_name='Longitude')),
            ],
            options={
                'verbose_name': 'Company',
            },
        ),
        migrations.CreateModel(
            name='DetailedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=256, null=True, verbose_name='Détail de la prescription')),
            ],
            options={
                'verbose_name': 'DetailedPost',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nom du métier')),
            ],
            options={
                'verbose_name': 'Job',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=128, unique=True, verbose_name='Nom du label')),
            ],
            options={
                'verbose_name': 'Label',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Profil du compte')),
            ],
            options={
                'verbose_name': 'Role',
            },
        ),
        migrations.CreateModel(
            name='ViewPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'ViewPost',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='Inconnu', max_length=128, verbose_name='Prénom')),
                ('lastName', models.CharField(default='Inconnu', max_length=128, verbose_name='Nom de famille')),
                ('proposer', models.IntegerField(default=None, null=True)),
                ('cellPhone', models.CharField(default=None, max_length=128, null=True, verbose_name='Téléphone mobile')),
                ('token', models.CharField(blank=True, default='empty token', max_length=512, null=True, verbose_name='Token de validation')),
                ('email', models.CharField(blank=True, default='Inconnu', max_length=128, null=True, verbose_name='Email')),
                ('password', models.CharField(blank=True, default='Inconnu', max_length=128, null=True, verbose_name='Mot de passe')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('userNameInternal', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du suivi')),
                ('comment', models.CharField(default=None, max_length=4906, null=True, verbose_name='Commentaire sur le suivi')),
                ('DetailedPost', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.detailedpost', verbose_name='Détail associé')),
                ('UserProfile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UserProfile', to='backBatiUni.userprofile')),
            ],
            options={
                'verbose_name': 'Supervision',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfPeople', models.IntegerField(default=1, verbose_name='Nombre de personne(s) demandées')),
                ('address', models.CharField(default=None, max_length=1024, null=True, verbose_name='Adresse du chantier')),
                ('latitude', models.FloatField(default=None, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(default=None, null=True, verbose_name='Longitude')),
                ('contactName', models.CharField(default=None, max_length=256, null=True, verbose_name='Nom du contact responsable de l’app')),
                ('draft', models.BooleanField(default=True, verbose_name='Brouillon ou validé')),
                ('manPower', models.BooleanField(default=True, verbose_name="Main d'oeuvre ou fourniture et pose")),
                ('dueDate', models.DateField(default=None, null=True, verbose_name="Date de d'échéance de l'annonce")),
                ('startDate', models.DateField(default=None, null=True, verbose_name='Date de début de chantier')),
                ('endDate', models.DateField(default=None, null=True, verbose_name='Date de fin de chantier')),
                ('hourlyStart', models.CharField(default=None, max_length=128, null=True, verbose_name='Horaire de début de chantier')),
                ('hourlyEnd', models.CharField(default=None, max_length=128, null=True, verbose_name='Horaire de fin de chantier')),
                ('amount', models.FloatField(default=0.0, verbose_name='Montant du chantier')),
                ('currency', models.CharField(default='€', max_length=128, null=True, verbose_name='Unité monétaire')),
                ('unitOfTime', models.CharField(default='Prix Journalier', max_length=128, null=True, verbose_name='Unité de temps')),
                ('counterOffer', models.BooleanField(default=False, verbose_name='Autoriser une contre offre')),
                ('description', models.CharField(default=None, max_length=4096, null=True, verbose_name='Description du chantier')),
                ('Company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Company', to='backBatiUni.company', verbose_name='Société demandeuse')),
                ('Job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.job', verbose_name='Métier')),
            ],
            options={
                'verbose_name': 'Post',
            },
        ),
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True, verbose_name='Date de disponibilité')),
                ('nature', models.CharField(default='Disponible', max_length=32, null=True, verbose_name='Disponibilité')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
            ],
            options={
                'verbose_name': 'Disponibility',
            },
        ),
        migrations.AddField(
            model_name='detailedpost',
            name='Post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Post', to='backBatiUni.post', verbose_name='Annonce associée'),
        ),
        migrations.AddField(
            model_name='company',
            name='Role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.role'),
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
            ],
            options={
                'verbose_name': 'Mission',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backBatiUni.post',),
        ),
        migrations.CreateModel(
            name='LabelForCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True, verbose_name='Date de péremption')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('Label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.label')),
            ],
            options={
                'verbose_name': 'LabelForCompany',
                'unique_together': {('Label', 'Company')},
            },
        ),
        migrations.CreateModel(
            name='JobForCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Nombre de profils ayant ce metier')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('Job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.job')),
            ],
            options={
                'verbose_name': 'JobForCompany',
                'unique_together': {('Job', 'Company')},
            },
        ),
        migrations.CreateModel(
            name='FavoritePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.IntegerField(blank=True, default=None, null=True, verbose_name='id du Post')),
                ('UserProfile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UserProfileforFavorite', to='backBatiUni.userprofile')),
            ],
            options={
                'verbose_name': 'FavoritePost',
                'unique_together': {('UserProfile', 'postId')},
            },
        ),
        migrations.AddField(
            model_name='detailedpost',
            name='Mission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Mission', to='backBatiUni.mission', verbose_name='Mission associée'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(default=False, max_length=128, verbose_name='nature du fichier')),
                ('name', models.CharField(default=False, max_length=128, verbose_name='Nom du fichier pour le front')),
                ('path', models.CharField(default=False, max_length=256, verbose_name='path')),
                ('ext', models.CharField(default=False, max_length=8, verbose_name='extension')),
                ('expirationDate', models.DateField(default=None, null=True, verbose_name='Date de péremption')),
                ('timestamp', models.FloatField(default=1645629881.811909, verbose_name='Timestamp de mise à jour')),
                ('Company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('Post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selectPost', to='backBatiUni.post', verbose_name='Annonce associée')),
                ('Supervision', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.supervision', verbose_name='Suivi associé')),
                ('Mission', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selectMission', to='backBatiUni.mission', verbose_name='Mission associée')),
            ],
            options={
                'verbose_name': 'File',
                'unique_together': {('nature', 'name', 'Company', 'Post', 'Mission', 'Supervision')},
            },
        ),
        migrations.CreateModel(
            name='DatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du chantier')),
                ('Post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostDate', to='backBatiUni.post', verbose_name='Annonce associée')),
                ('Mission', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MissionDate', to='backBatiUni.mission', verbose_name='Mission associée')),
            ],
            options={
                'verbose_name': 'DatePost',
                'unique_together': {('Post', 'Mission', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isChoosen', models.BooleanField(default=None, null=True, verbose_name='Sous traitant selectionné')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name="Date de candidature ou date d'acceptation")),
                ('amount', models.FloatField(default=0.0, verbose_name='Prix unitaire')),
                ('unitOfTime', models.CharField(default='Prix Journalier', max_length=128, null=True, verbose_name='Unité de temps')),
                ('Company', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selecteCompany', to='backBatiUni.company', verbose_name='Sous-Traitant')),
                ('Post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='backBatiUni.post', verbose_name='Annonce associée')),
                ('Mission', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectedMission', to='backBatiUni.mission', verbose_name='Mission associée')),
            ],
            options={
                'verbose_name': 'Candidate',
                'unique_together': {('Post', 'Mission', 'Company')},
            },
        ),
    ]
