# Generated by Django 4.0 on 2022-01-13 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nom de la société')),
                ('siret', models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name='Numéro de Siret')),
                ('capital', models.IntegerField(default=None, null=True, verbose_name="Capital de l'entreprise")),
                ('revenue', models.FloatField(default=None, null=True, verbose_name="Capital de l'entreprise")),
                ('logo', models.CharField(default=None, max_length=256, null=True, verbose_name="Path du logo de l'entreprise")),
                ('webSite', models.CharField(default=None, max_length=256, null=True, verbose_name='Url du site Web')),
                ('stars', models.IntegerField(default=None, null=True, verbose_name="Notation sous forme d'étoile")),
                ('companyPhone', models.CharField(default=None, max_length=128, null=True, verbose_name='Téléphone du standard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nom du métier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=128, unique=True, verbose_name='Nom du label')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Profil du compte')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='Inconnu', max_length=128, verbose_name='Prénom')),
                ('lastName', models.CharField(default='Inconnu', max_length=128, verbose_name='Nom de famille')),
                ('proposer', models.IntegerField(default=None, null=True)),
                ('cellPhone', models.CharField(default=None, max_length=128, null=True, verbose_name='Téléphone mobile')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.role')),
                ('userNameInternal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='auth.user')),
            ],
            options={
                'verbose_name': 'UserProfile',
            },
        ),
        migrations.CreateModel(
            name='LabelForCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True, verbose_name='Date de péremption')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.label')),
            ],
            options={
                'unique_together': {('label', 'company')},
            },
        ),
        migrations.CreateModel(
            name='JobForCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Nombre de profils ayant ce metier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.job')),
            ],
            options={
                'unique_together': {('job', 'company')},
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(default=False, max_length=128, unique=True, verbose_name='nature du fichier')),
                ('name', models.CharField(default=False, max_length=128, unique=True, verbose_name='Nom du fichier pour le front')),
                ('path', models.CharField(default=False, max_length=256, verbose_name='path')),
                ('ext', models.CharField(default=False, max_length=8, unique=True, verbose_name='extension')),
                ('expirationDate', models.DateField(default=None, null=True, verbose_name='Date de péremption')),
                ('timestamp', models.FloatField(default=1642090481.256843, verbose_name='Timestamp de mise à jour')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
            ],
            options={
                'verbose_name': 'Files',
                'unique_together': {('nature', 'name', 'company')},
            },
        ),
    ]
