# Generated by Django 4.0.2 on 2022-02-23 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewpost',
            name='UserProfile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UserProfileforView', to='backBatiUni.userprofile'),
        ),
        migrations.AddField(
            model_name='viewpost',
            name='postId',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='id du Post'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645631083.25153, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterUniqueTogether(
            name='viewpost',
            unique_together={('UserProfile', 'postId')},
        ),
    ]
