# Generated by Django 4.0 on 2022-01-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0002_alter_files_company_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='nature',
            field=models.CharField(default=False, max_length=128, verbose_name='nature du fichier'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642148567.908429, verbose_name='Timestamp de mise à jour'),
        ),
    ]
