# Generated by Django 4.0 on 2022-01-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0002_role_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='jobs',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='jobs',
            field=models.ManyToManyField(to='backBatiUni.Job'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='proposer',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
