# Generated by Django 4.0 on 2022-01-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0003_alter_files_nature_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='ext',
            field=models.CharField(default=False, max_length=8, verbose_name='extension'),
        ),
        migrations.AlterField(
            model_name='files',
            name='name',
            field=models.CharField(default=False, max_length=128, verbose_name='Nom du fichier pour le front'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642148614.671745, verbose_name='Timestamp de mise à jour'),
        ),
    ]
