# Generated by Django 4.0.2 on 2022-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0003_post_contract_post_signedbycompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedpost',
            name='date',
            field=models.DateField(default=None, null=True, verbose_name='Date de la tâche'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1646664418.483701, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='signedByCompany',
            field=models.BooleanField(default=False, verbose_name='Signature de la PME'),
        ),
        migrations.AlterField(
            model_name='post',
            name='signedBySubContractor',
            field=models.BooleanField(default=False, verbose_name='Signature du ST'),
        ),
    ]
