# Generated by Django 4.0 on 2022-01-04 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0003_remove_userprofile_jobs_userprofile_jobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(default=None, max_length=32, verbose_name='Numéro de Siret'),
        ),
    ]
