# Generated by Django 4.0.2 on 2022-03-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0004_detailedpost_date_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedpost',
            name='validated',
            field=models.BooleanField(default=None, null=True, verbose_name='Validation de la tache'),
        ),
        migrations.AddField(
            model_name='supervision',
            name='Mission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AssociatedMission', to='backBatiUni.mission', verbose_name='Mission associée'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1646737107.780036, verbose_name='Timestamp de mise à jour'),
        ),
    ]
