# Generated by Django 4.0 on 2022-01-04 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0004_alter_company_siret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='siret',
            field=models.CharField(default=None, max_length=32, null=True, verbose_name='Numéro de Siret'),
        ),
    ]
