# Generated by Django 4.0.2 on 2022-03-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0005_detailedpost_validated_supervision_mission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedpost',
            name='validated',
            field=models.BooleanField(default=False, verbose_name='Validation de la tache'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1646833592.946586, verbose_name='Timestamp de mise à jour'),
        ),
    ]
