# Generated by Django 4.0 on 2022-01-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0005_rename_company_files_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobforcompany',
            old_name='job',
            new_name='Job',
        ),
        migrations.RenameField(
            model_name='labelforcompany',
            old_name='label',
            new_name='Label',
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642156579.837905, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterUniqueTogether(
            name='jobforcompany',
            unique_together={('Job', 'Company')},
        ),
        migrations.AlterUniqueTogether(
            name='labelforcompany',
            unique_together={('Label', 'Company')},
        ),
    ]
