# Generated by Django 4.0.2 on 2022-03-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0006_alter_detailedpost_validated_alter_file_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1646902551.76274, verbose_name='Timestamp de mise à jour'),
        ),
    ]
