# Generated by Django 4.0 on 2022-01-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0006_label_company_capital_company_logo_company_stars_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='user',
            new_name='userInternal',
        ),
    ]
