# Generated by Django 4.0 on 2022-01-15 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0007_alter_files_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default='empty token', max_length=32, verbose_name='token de validation'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642266154.698325, verbose_name='Timestamp de mise à jour'),
        ),
    ]
