# Generated by Django 4.0.2 on 2022-03-10 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0007_alter_file_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subContractorName',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Contact chez le sous traitant'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1646902751.918776, verbose_name='Timestamp de mise à jour'),
        ),
    ]
