# Generated by Django 4.0 on 2022-01-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0008_alter_role_options_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={},
        ),
        migrations.AddField(
            model_name='company',
            name='companyPhone',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Téléphone du standard'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cellPhone',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Téléphone mobile'),
        ),
    ]
