# Generated by Django 4.0 on 2022-01-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0008_userprofile_token_alter_files_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(default='Inconnu', max_length=128, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password',
            field=models.CharField(default='Inconnu', max_length=128, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642268299.151632, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default='empty token', max_length=32, verbose_name='Token de validation'),
        ),
    ]
