# Generated by Django 4.0.2 on 2022-03-15 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0008_post_subcontractorname_alter_file_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedpost',
            name='refused',
            field=models.BooleanField(default=False, verbose_name='Refus de validation de la tache'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647373204.740921, verbose_name='Timestamp de mise à jour'),
        ),
    ]
