# Generated by Django 4.0 on 2022-01-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0009_userprofile_email_userprofile_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642407216.874335, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.CharField(blank=True, default='Inconnu', max_length=128, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(blank=True, default='Inconnu', max_length=128, null=True, verbose_name='Mot de passe'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, default='empty token', max_length=32, null=True, verbose_name='Token de validation'),
        ),
    ]
