# Generated by Django 4.0 on 2022-01-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0010_alter_files_timestamp_alter_userprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='description',
            field=models.CharField(default=None, max_length=2048, verbose_name='Description du métier'),
        ),
        migrations.AddField(
            model_name='role',
            name='site',
            field=models.CharField(default=None, max_length=256, verbose_name='Site internet'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642417481.32049, verbose_name='Timestamp de mise à jour'),
        ),
    ]
