# Generated by Django 4.0.2 on 2022-03-18 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0010_remove_supervision_mission_supervision_supervisionid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='Mission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.mission', verbose_name='Mission associée'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647601524.990286, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='DetailedPost',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.detailedpost', verbose_name='Tâche associée'),
        ),
    ]
