# Generated by Django 4.0 on 2022-01-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0010_rename_userinternal_userprofile_usernameinternal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='jobs',
        ),
        migrations.AddField(
            model_name='company',
            name='revenue',
            field=models.FloatField(default=None, null=True, verbose_name="Capital de l'entreprise"),
        ),
        migrations.CreateModel(
            name='JobForCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='Nombre de profils ayant ce metier')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.job')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
