# Generated by Django 4.0 on 2022-01-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0011_role_description_role_site_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642417596.960517, verbose_name='Timestamp de mise à jour'),
        ),
    ]
