# Generated by Django 4.0.2 on 2022-03-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0011_supervision_mission_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647601665.222043, verbose_name='Timestamp de mise à jour'),
        ),
    ]
