# Generated by Django 4.0 on 2022-01-11 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0011_remove_userprofile_jobs_company_revenue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='labels',
        ),
        migrations.AlterUniqueTogether(
            name='jobforcompany',
            unique_together={('job', 'company')},
        ),
        migrations.CreateModel(
            name='LabelForCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True, verbose_name='Date de péremption')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.label')),
            ],
            options={
                'unique_together': {('label', 'company')},
            },
        ),
    ]
