# Generated by Django 4.0 on 2022-01-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0012_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642417655.294072, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.CharField(default=None, max_length=2048, null=True, verbose_name='Description du métier'),
        ),
        migrations.AlterField(
            model_name='role',
            name='site',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Site internet'),
        ),
    ]
