# Generated by Django 4.0.2 on 2022-03-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0012_alter_file_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervision',
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='supervision',
            name='author',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name="Nom de l'auteur du message"),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647603017.159429, verbose_name='Timestamp de mise à jour'),
        ),
    ]
