# Generated by Django 4.0 on 2022-01-13 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0012_remove_company_labels_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(default=False, max_length=128, unique=True, verbose_name='nature du fichier')),
                ('name', models.CharField(default=False, max_length=128, unique=True, verbose_name='Nom du fichier pour le front')),
                ('path', models.CharField(default=False, max_length=256, unique=True, verbose_name='path')),
                ('ext', models.CharField(default=False, max_length=8, unique=True, verbose_name='extension')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.userprofile')),
            ],
        ),
    ]
