# Generated by Django 4.0.2 on 2022-03-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0013_remove_supervision_userprofile_supervision_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647607520.067416, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='superVisionId',
            field=models.IntegerField(default=-1, verbose_name="id de la supervision dans le cas d'une réponse"),
        ),
    ]
