# Generated by Django 4.0 on 2022-01-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0013_alter_files_timestamp_alter_role_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='description',
        ),
        migrations.RemoveField(
            model_name='role',
            name='site',
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642426290.413222, verbose_name='Timestamp de mise à jour'),
        ),
    ]
