# Generated by Django 4.0 on 2022-01-13 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0013_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='path',
            field=models.CharField(default=False, max_length=256, verbose_name='path'),
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('nature', 'name', 'user')},
        ),
    ]
