# Generated by Django 4.0 on 2022-01-17 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0014_remove_role_description_remove_role_site_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1642427139.689898, verbose_name='Timestamp de mise à jour'),
        ),
    ]
