# Generated by Django 4.0 on 2022-01-13 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0014_alter_files_path_alter_files_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name': 'Files'},
        ),
        migrations.RenameField(
            model_name='files',
            old_name='user',
            new_name='userProfile',
        ),
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('nature', 'name', 'userProfile')},
        ),
    ]
