# Generated by Django 4.0.2 on 2022-03-21 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0015_remove_supervision_supervisionid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervision',
            old_name='Supervision',
            new_name='SupervisionAssociated',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647853773.604337, verbose_name='Timestamp de mise à jour'),
        ),
    ]
