# Generated by Django 4.0 on 2022-01-24 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0015_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643034408.153756, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='token',
            field=models.CharField(blank=True, default='empty token', max_length=512, null=True, verbose_name='Token de validation'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfPeople', models.IntegerField(default=1, verbose_name='Nombre de personne(s) demandées')),
                ('manPower', models.BooleanField(default=True, verbose_name="Main d'oeuvre ou fourniture et pose")),
                ('dueDate', models.DateField(default=None, null=True, verbose_name="Date de d'échéance de l'annonce")),
                ('startDate', models.DateField(default=None, null=True, verbose_name='Date de début de chantier')),
                ('endDate', models.DateField(default=None, null=True, verbose_name='Date de fin de chantier')),
                ('hourlyStart', models.CharField(default=None, max_length=128, null=True, verbose_name='Horaire de début de chantier')),
                ('hourlyEnd', models.CharField(default=None, max_length=128, null=True, verbose_name='Horaire de fin de chantier')),
                ('amount', models.FloatField(default=0.0, verbose_name='Montant du chantier')),
                ('currency', models.CharField(default='Euro', max_length=128, null=True, verbose_name='Unité monétaire')),
                ('counterOffer', models.BooleanField(default=False, verbose_name='Autoriser une contre offre')),
                ('description', models.CharField(default=None, max_length=4096, null=True, verbose_name='Description du chantier')),
                ('Company', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company', verbose_name='Société demandeuse')),
                ('Job', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.job', verbose_name='Métier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetailedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default=None, max_length=256, null=True, verbose_name='Détail de la presciption')),
                ('Post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.post', verbose_name='Annonce associée')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
