# Generated by Django 4.0.2 on 2022-03-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0016_rename_supervision_supervision_supervisionassociated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='DetailedPost',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='AssociatedDetailedPost', to='backBatiUni.detailedpost', verbose_name='Tâche associée'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647867978.587207, verbose_name='Timestamp de mise à jour'),
        ),
    ]
