# Generated by Django 4.0 on 2022-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0016_alter_files_timestamp_alter_userprofile_token_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643122876.354252, verbose_name='Timestamp de mise à jour'),
        ),
    ]
