# Generated by Django 4.0 on 2022-01-25 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0017_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailedpost',
            name='Post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.post', verbose_name='Annonce associée'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643123774.106136, verbose_name='Timestamp de mise à jour'),
        ),
    ]
