# Generated by Django 4.0.2 on 2022-03-22 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0017_file_detailedpost_alter_file_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='DetailedPost',
        ),
        migrations.AddField(
            model_name='company',
            name='allJobs',
            field=models.BooleanField(default=True, verbose_name="Tous corps d'état"),
        ),
        migrations.AddField(
            model_name='company',
            name='saturdayDisponibility',
            field=models.BooleanField(default=True, verbose_name='Disponibilité le Samedi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='function',
            field=models.CharField(blank=True, default='', max_length=128, null=True, verbose_name="Fonction dans l'entreprise"),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647970614.199071, verbose_name='Timestamp de mise à jour'),
        ),
    ]
