# Generated by Django 4.0 on 2022-01-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0018_alter_detailedpost_post_alter_files_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='draft',
            field=models.BooleanField(default=True, verbose_name='Brouillon ou validé'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643125212.051805, verbose_name='Timestamp de mise à jour'),
        ),
    ]
