# Generated by Django 4.0.2 on 2022-03-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0018_remove_file_detailedpost_company_alljobs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='allJobs',
            field=models.BooleanField(default=False, verbose_name="Tous corps d'état"),
        ),
        migrations.AlterField(
            model_name='company',
            name='saturdayDisponibility',
            field=models.BooleanField(default=False, verbose_name='Disponibilité le Samedi'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647970863.270379, verbose_name='Timestamp de mise à jour'),
        ),
    ]
