# Generated by Django 4.0.2 on 2022-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0019_alter_company_alljobs_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='allJobs',
            new_name='allQualifications',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1647974790.708679, verbose_name='Timestamp de mise à jour'),
        ),
    ]
