# Generated by Django 4.0 on 2022-01-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0019_post_draft_alter_files_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='address',
            field=models.CharField(default=None, max_length=1024, null=True, verbose_name='Adresse du chantier'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643125620.093786, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='currency',
            field=models.CharField(default='€', max_length=128, null=True, verbose_name='Unité monétaire'),
        ),
    ]
