# Generated by Django 4.0.2 on 2022-03-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0020_rename_alljobs_company_allqualifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='activity',
            field=models.CharField(default='', max_length=256, verbose_name="Activite principale de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1648463123.609023, verbose_name='Timestamp de mise à jour'),
        ),
    ]
