# Generated by Django 4.0 on 2022-01-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0021_post_contactname_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643195479.882862, verbose_name='Timestamp de mise à jour'),
        ),
    ]
