# Generated by Django 4.0.2 on 2022-04-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0021_alter_company_activity_alter_file_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subContractorContact',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Contact chez le sous traitant'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1648835491.40061, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='contactName',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Nom du contact responsable de la mission'),
        ),
        migrations.AlterField(
            model_name='post',
            name='subContractorName',
            field=models.CharField(default=None, max_length=128, null=True, verbose_name='Nom le sous traitant'),
        ),
    ]
