# Generated by Django 4.0 on 2022-01-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0022_alter_files_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='activity',
            field=models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name="Activite principale de l'entreprise"),
        ),
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name="Adresse de l'entreprise"),
        ),
        migrations.AddField(
            model_name='company',
            name='ntva',
            field=models.CharField(default=None, max_length=32, null=True, unique=True, verbose_name='Numéro de TVA intra communautaire'),
        ),
        migrations.AddField(
            model_name='files',
            name='Post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.post', verbose_name='Annonce associée'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643281464.630126, verbose_name='Timestamp de mise à jour'),
        ),
    ]
