# Generated by Django 4.0 on 2022-01-27 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0023_company_activity_company_address_company_ntva_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supervision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True, verbose_name='Date du suivi')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('backBatiUni.post',),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='company',
            name='role',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.role'),
        ),
        migrations.AddField(
            model_name='post',
            name='subContractor',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subContractor', to='backBatiUni.company', verbose_name='Société sous-traitante'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643298192.602254, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='Company', to='backBatiUni.company', verbose_name='Société demandeuse'),
        ),
    ]
