# Generated by Django 4.0 on 2022-01-27 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0025_detailedpost_mission_alter_detailedpost_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='DetailedPost',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.detailedpost', verbose_name='Détail associé'),
        ),
        migrations.AddField(
            model_name='supervision',
            name='commment',
            field=models.CharField(default=None, max_length=4906, null=True, verbose_name='Commentaire sur le suivi'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643301501.895079, verbose_name='Timestamp de mise à jour'),
        ),
    ]
