# Generated by Django 4.0.2 on 2022-04-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0025_post_organisation_post_organisationcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isClosed',
            field=models.BooleanField(default=False, verbose_name='Fin de la mission'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649233779.587301, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='organisation',
            field=models.IntegerField(default=0, verbose_name='Organisation'),
        ),
        migrations.AlterField(
            model_name='post',
            name='quality',
            field=models.IntegerField(default=0, verbose_name='Qualité du travail fourni'),
        ),
        migrations.AlterField(
            model_name='post',
            name='security',
            field=models.IntegerField(default=0, verbose_name='Respect de la sécurité et de la propreté du chantier'),
        ),
    ]
