# Generated by Django 4.0.2 on 2022-04-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0026_post_isclosed_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='companyId',
            field=models.IntegerField(blank=True, default=None, verbose_name='Id de la companie emettrice'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649344562.860208, verbose_name='Timestamp de mise à jour'),
        ),
    ]
