# Generated by Django 4.0 on 2022-01-27 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0026_supervision_detailedpost_supervision_commment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Supervision',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.supervision', verbose_name='Suivi associé'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643306309.9719, verbose_name='Timestamp de mise à jour'),
        ),
    ]
