# Generated by Django 4.0.2 on 2022-04-07 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0027_supervision_companyid_alter_file_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='isRefused',
            field=models.BooleanField(default=False, null=True, verbose_name='Sous traitant refusé'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='isChoosen',
            field=models.BooleanField(default=False, null=True, verbose_name='Sous traitant selectionné'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1649354026.100935, verbose_name='Timestamp de mise à jour'),
        ),
    ]
