# Generated by Django 4.0 on 2022-01-31 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0027_files_supervision_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('nature', 'name', 'Company', 'Post', 'Supervision')},
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643646961.467537, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.CreateModel(
            name='Disponibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None, null=True, verbose_name='Date de péremption')),
                ('Company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
