# Generated by Django 4.0 on 2022-01-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0028_alter_files_unique_together_alter_files_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibility',
            name='nature',
            field=models.CharField(default='Disponible', max_length=32, null=True, verbose_name='Disponibilité'),
        ),
        migrations.AlterField(
            model_name='disponibility',
            name='date',
            field=models.DateField(default=None, null=True, verbose_name='Date de disponibilité'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643651300.458655, verbose_name='Timestamp de mise à jour'),
        ),
    ]
