# Generated by Django 4.0 on 2022-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0029_disponibility_nature_alter_disponibility_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=256, null=True, unique=True, verbose_name="Adresse de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643725808.959813, verbose_name='Timestamp de mise à jour'),
        ),
    ]
