# Generated by Django 4.0 on 2022-02-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0032_alter_files_timestamp_alter_post_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=None, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=None, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643969086.107978, verbose_name='Timestamp de mise à jour'),
        ),
    ]
