# Generated by Django 4.0 on 2022-02-04 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0033_post_latitude_post_longitude_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1643969486.379151, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='post',
            name='latitude',
            field=models.FloatField(default=None, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='post',
            name='longitude',
            field=models.FloatField(default=None, null=True, verbose_name='Longitude'),
        ),
    ]
