# Generated by Django 4.0 on 2022-02-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0037_rename_lattitude_post_latitude_remove_post_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='company', to='backBatiUni.company', verbose_name='Société demandeuse'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644312882.085623, verbose_name='Timestamp de mise à jour'),
        ),
    ]
