# Generated by Django 4.0 on 2022-02-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0038_post_company_alter_files_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Company',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='company',
        ),
        migrations.RemoveField(
            model_name='detailedpost',
            name='Post',
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644313088.942063, verbose_name='Timestamp de mise à jour'),
        ),
    ]
