# Generated by Django 4.0 on 2022-02-08 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0040_rename_company_post_company_alter_files_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailedpost',
            name='Post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='post', to='backBatiUni.post', verbose_name='Annonce associée'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644313148.276332, verbose_name='Timestamp de mise à jour'),
        ),
    ]
