# Generated by Django 4.0 on 2022-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0042_alter_files_timestamp_alter_post_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644313195.698323, verbose_name='Timestamp de mise à jour'),
        ),
    ]
