# Generated by Django 4.0 on 2022-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0045_candidate_annonce_alter_files_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='annonce',
            new_name='Post',
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644313343.740365, verbose_name='Timestamp de mise à jour'),
        ),
    ]
