# Generated by Django 4.0 on 2022-02-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0047_candidate_subcontractor_alter_files_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='subcontractor',
            new_name='subContractor',
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644316861.522344, verbose_name='Timestamp de mise à jour'),
        ),
    ]
