# Generated by Django 4.0 on 2022-02-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0048_rename_subcontractor_candidate_subcontractor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='subContractor',
            new_name='Company',
        ),
        migrations.AddField(
            model_name='candidate',
            name='Mission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selectedMission', to='backBatiUni.mission', verbose_name='Mission associée'),
        ),
        migrations.AlterField(
            model_name='detailedpost',
            name='Post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Post', to='backBatiUni.post', verbose_name='Annonce associée'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644317557.249628, verbose_name='Timestamp de mise à jour'),
        ),
    ]
