# Generated by Django 4.0 on 2022-02-08 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0049_rename_subcontractor_candidate_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644332242.311132, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('Post', 'Mission', 'Company')},
        ),
    ]
