# Generated by Django 4.0 on 2022-02-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0050_alter_files_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='Company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selecteCompany', to='backBatiUni.company', verbose_name='Sous-Traitant'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644332347.896482, verbose_name='Timestamp de mise à jour'),
        ),
    ]
