# Generated by Django 4.0 on 2022-02-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0051_alter_candidate_company_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644332389.804866, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='Company',
        ),
    ]
