# Generated by Django 4.0 on 2022-02-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0052_alter_candidate_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644332455.527587, verbose_name='Timestamp de mise à jour'),
        ),
    ]
