# Generated by Django 4.0 on 2022-02-08 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0056_alter_files_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervision',
            name='UserProfile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.userprofile', verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644334169.45811, verbose_name='Timestamp de mise à jour'),
        ),
    ]
