# Generated by Django 4.0 on 2022-02-08 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0057_supervision_userprofile_alter_files_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='Mission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selectMission', to='backBatiUni.mission', verbose_name='Mission associée'),
        ),
        migrations.AlterField(
            model_name='files',
            name='Post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selectPost', to='backBatiUni.post', verbose_name='Annonce associée'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644335468.688839, verbose_name='Timestamp de mise à jour'),
        ),
    ]
