# Generated by Django 4.0 on 2022-02-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0058_files_mission_alter_files_post_alter_files_timestamp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='files',
            unique_together={('nature', 'name', 'Company', 'Post', 'Mission', 'Supervision')},
        ),
        migrations.RemoveField(
            model_name='supervision',
            name='UserProfile',
        ),
        migrations.AddField(
            model_name='supervision',
            name='author',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Détail de la presciption'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644340542.513306, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='date',
            field=models.DateField(default='2022-02-08', verbose_name='Date du suivi'),
        ),
    ]
