# Generated by Django 4.0 on 2022-02-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0059_alter_files_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supervision',
            old_name='commment',
            new_name='comment',
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644340612.640044, verbose_name='Timestamp de mise à jour'),
        ),
    ]
