# Generated by Django 4.0 on 2022-02-09 16:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0060_rename_commment_supervision_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 17, 50, 54, 995715), verbose_name="Date de candidateur ou date d'acceptation"),
        ),
        migrations.AlterField(
            model_name='detailedpost',
            name='content',
            field=models.CharField(default=None, max_length=256, null=True, verbose_name='Détail de la prescription'),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644425454.997051, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 17, 50, 54, 996583), verbose_name='Date du suivi'),
        ),
    ]
