# Generated by Django 4.0 on 2022-02-09 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0061_candidate_date_alter_detailedpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 17, 53, 57, 418766), verbose_name="Date de candidateur ou date d'acceptation"),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644425637.419795, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 17, 53, 57, 419425), verbose_name='Date du suivi'),
        ),
    ]
