# Generated by Django 4.0 on 2022-02-09 16:54

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0062_alter_candidate_date_alter_files_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date de candidateur ou date d'acceptation"),
        ),
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644425661.093648, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 9, 17, 54, 21, 93321), verbose_name='Date du suivi'),
        ),
    ]
