# Generated by Django 4.0 on 2022-02-09 16:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0063_alter_candidate_date_alter_files_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='timestamp',
            field=models.FloatField(default=1644425722.645337, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterField(
            model_name='supervision',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date du suivi'),
        ),
    ]
