# Generated by Django 4.0 on 2022-02-09 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0064_alter_files_timestamp_alter_supervision_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nature', models.CharField(default=False, max_length=128, verbose_name='nature du fichier')),
                ('name', models.CharField(default=False, max_length=128, verbose_name='Nom du fichier pour le front')),
                ('path', models.CharField(default=False, max_length=256, verbose_name='path')),
                ('ext', models.CharField(default=False, max_length=8, verbose_name='extension')),
                ('expirationDate', models.DateField(default=None, null=True, verbose_name='Date de péremption')),
                ('timestamp', models.FloatField(default=1644426889.580461, verbose_name='Timestamp de mise à jour')),
            ],
            options={
                'verbose_name': 'File',
            },
        ),
        migrations.RenameField(
            model_name='company',
            old_name='role',
            new_name='Role',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AddField(
            model_name='file',
            name='Company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.company'),
        ),
        migrations.AddField(
            model_name='file',
            name='Mission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selectMission', to='backBatiUni.mission', verbose_name='Mission associée'),
        ),
        migrations.AddField(
            model_name='file',
            name='Post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='selectPost', to='backBatiUni.post', verbose_name='Annonce associée'),
        ),
        migrations.AddField(
            model_name='file',
            name='Supervision',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='backBatiUni.supervision', verbose_name='Suivi associé'),
        ),
        migrations.AlterUniqueTogether(
            name='file',
            unique_together={('nature', 'name', 'Company', 'Post', 'Mission', 'Supervision')},
        ),
    ]
