# Generated by Django 4.0 on 2022-02-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0065_file_rename_role_company_role_delete_files_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidate',
            options={'verbose_name': 'Candidate'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='detailedpost',
            options={'verbose_name': 'DetailedPost'},
        ),
        migrations.AlterModelOptions(
            name='disponibility',
            options={'verbose_name': 'Disponibility'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'Job'},
        ),
        migrations.AlterModelOptions(
            name='jobforcompany',
            options={'verbose_name': 'JobForCompany'},
        ),
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Label'},
        ),
        migrations.AlterModelOptions(
            name='labelforcompany',
            options={'verbose_name': 'LabelForCompany'},
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'verbose_name': 'Mission'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'Role'},
        ),
        migrations.AlterModelOptions(
            name='supervision',
            options={'verbose_name': 'Supervision'},
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1644587720.084915, verbose_name='Timestamp de mise à jour'),
        ),
    ]
