# Generated by Django 4.0 on 2022-02-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0066_alter_candidate_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1644834970.828613, verbose_name='Timestamp de mise à jour'),
        ),
    ]
