# Generated by Django 4.0 on 2022-02-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0067_alter_file_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='amount',
            field=models.FloatField(default=None, null=True, verbose_name='Montant sous-traitant'),
        ),
        migrations.AddField(
            model_name='company',
            name='latitude',
            field=models.FloatField(default=None, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='longitude',
            field=models.FloatField(default=None, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='unity',
            field=models.CharField(default=None, max_length=64, null=True, verbose_name='Unité du montant'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1644853572.262857, verbose_name='Timestamp de mise à jour'),
        ),
    ]
