# Generated by Django 4.0 on 2022-02-16 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0069_alter_candidate_ischoosen_alter_file_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name="Date de candidature ou date d'acceptation"),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645002697.074776, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.CreateModel(
            name='DatePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date du chantier')),
                ('Mission', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MissionDate', to='backBatiUni.mission', verbose_name='Mission associée')),
                ('Post', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='PostDate', to='backBatiUni.post', verbose_name='Annonce associée')),
            ],
            options={
                'verbose_name': 'DatePost',
                'unique_together': {('Post', 'Mission', 'date')},
            },
        ),
    ]
