# Generated by Django 4.0 on 2022-02-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0070_alter_candidate_date_alter_file_timestamp_datepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datepost',
            old_name='date',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645005080.631131, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterUniqueTogether(
            name='datepost',
            unique_together={('Post', 'Mission', 'content')},
        ),
    ]
