# Generated by Django 4.0 on 2022-02-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0071_rename_date_datepost_content_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datepost',
            old_name='content',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645020535.257416, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterUniqueTogether(
            name='datepost',
            unique_together={('Post', 'Mission', 'date')},
        ),
    ]
