# Generated by Django 4.0 on 2022-02-16 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0072_rename_content_datepost_date_alter_file_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='amount',
            field=models.FloatField(default=0.0, verbose_name='Prix unitaire'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='unitOfTime',
            field=models.CharField(default='Prix Journalier', max_length=128, null=True, verbose_name='Unité de temps'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645022239.756554, verbose_name='Timestamp de mise à jour'),
        ),
    ]
