# Generated by Django 4.0.2 on 2022-02-21 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0073_candidate_amount_candidate_unitoftime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645458195.823903, verbose_name='Timestamp de mise à jour'),
        ),
    ]
