# Generated by Django 4.0.2 on 2022-02-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0075_alter_file_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645458944.241402, verbose_name='Timestamp de mise à jour'),
        ),
    ]
