# Generated by Django 4.0.2 on 2022-02-22 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0077_alter_file_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervision',
            name='author',
        ),
        migrations.AddField(
            model_name='supervision',
            name='Company',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subContractor', to='backBatiUni.company'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645542645.871907, verbose_name='Timestamp de mise à jour'),
        ),
    ]
