# Generated by Django 4.0.2 on 2022-02-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0078_remove_supervision_author_supervision_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645545954.624474, verbose_name='Timestamp de mise à jour'),
        ),
    ]
