# Generated by Django 4.0.2 on 2022-02-22 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0079_alter_file_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervision',
            name='Company',
        ),
        migrations.AddField(
            model_name='supervision',
            name='UserProfile',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='UserProfile', to='backBatiUni.userprofile'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645546091.125136, verbose_name='Timestamp de mise à jour'),
        ),
    ]
