# Generated by Django 4.0.2 on 2022-02-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0080_remove_supervision_company_supervision_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645606308.681897, verbose_name='Timestamp de mise à jour'),
        ),
    ]
