# Generated by Django 4.0.2 on 2022-02-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0081_alter_file_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite',
            field=models.BooleanField(default=False, verbose_name='Favori'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nbViews',
            field=models.IntegerField(default=0, verbose_name='nb vues'),
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645606492.199438, verbose_name='Timestamp de mise à jour'),
        ),
    ]
