# Generated by Django 4.0.2 on 2022-02-23 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0082_userprofile_favorite_userprofile_nbviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nbViews',
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645612035.981662, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postId', models.IntegerField(blank=True, default=None, null=True, verbose_name='id du Post')),
                ('UserProfile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relatedUserProfile', to='backBatiUni.userprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
