# Generated by Django 4.0.2 on 2022-02-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0083_remove_userprofile_favorite_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorite',
            new_name='FavoritePost',
        ),
        migrations.AlterModelOptions(
            name='favoritepost',
            options={'verbose_name': 'Favorite'},
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645615423.503533, verbose_name='Timestamp de mise à jour'),
        ),
        migrations.AlterUniqueTogether(
            name='favoritepost',
            unique_together={('UserProfile', 'postId')},
        ),
    ]
