# Generated by Django 4.0.2 on 2022-02-23 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backBatiUni', '0084_rename_favorite_favoritepost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewPost',
            fields=[
                ('favoritepost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='backBatiUni.favoritepost')),
            ],
            options={
                'verbose_name': 'ViewPost',
            },
            bases=('backBatiUni.favoritepost',),
        ),
        migrations.AlterModelOptions(
            name='favoritepost',
            options={'verbose_name': 'FavoritePost'},
        ),
        migrations.AlterField(
            model_name='file',
            name='timestamp',
            field=models.FloatField(default=1645624060.68946, verbose_name='Timestamp de mise à jour'),
        ),
    ]
